apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-client-debugger
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/francescopezzulli/argocd-playground.git
    targetRevision: main
    path: manifests/oidc-client-debugger
  destination:
    server: https://kubernetes.default.svc
    namespace: francesco-onboarding
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
