apiVersion: v1
kind: Service
metadata:
  name: oidc-client-debugger-git
  namespace: francesco-onboarding
  labels:
    app: oidc-client-debugger-git
    app.kubernetes.io/component: oidc-client-debugger-git
    app.kubernetes.io/instance: oidc-client-debugger-git
    app.kubernetes.io/name: oidc-client-debugger-git
    app.kubernetes.io/part-of: oidc-client-debugger-git-app
spec:
  selector:
    app: oidc-client-debugger-git
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: 8443-tcp
      port: 8443
      targetPort: 8443
      protocol: TCP
